services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=splearn'
      - 'MYSQL_PASSWORD=1111'
      - 'MYSQL_ROOT_PASSWORD=1111'
      - 'MYSQL_USER=user'
    ports:
      - '3306:3306'